language: python
python: 3.7
dist: xenial
sudo: true

# Install dependencies
install:
  - python -m pip install codecov
  - python -m pip install poetry
  - poetry install

# Run Tests
script:
  - bash run-tests.sh
after_success:
  - codecov
