language: python
python: 3.7
dist: xenial

# Install dependencies
install:
  - pip install -r requirements.txt

# Run Tests
script: 
  - python -m pip install -U https://github.com/Rapptz/discord.py/archive/master.zip#egg=discord.py
  - python -m unittest discover