[tool.poetry]
name = "doob_bot"
version = "0.1.0"
description = "A Simple Raider.io bot for Discord"
authors = ["Stephen Onnen <stephen.onnen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
"discord.py" = "^1.2"
requests = "^2.22"
spylogger = "^1.2"
wheel = "^0.33.6"

[tool.poetry.dev-dependencies]
mock = "^3.0"
coverage = "^4.5"
pytest = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
