version: 2.1
orgs:
  codecov: codecov/codecov@1.02
jobs:
  build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install codecov
      - run: pip install -U https://github.com/Rapptz/discord.py/archive/rewrite.zip#egg=discord.py
      - run: pip install -e .
      - run: bash run-tests.sh
      - codecov/upload:
        file: .coverage
