name: CI Test
on: [push]

jobs:
  test:
    - name: Test
      runs-on: ubuntu-latest
      run: |
        - python -m pip install -r requirements.txt
        - python -m pip install -e .
        - bash run-tests.sh
