name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          sudo apt-get install -y python3-setuptools
          python3 -m pip install poetry
          poetry install
          bash run-tests.sh
