name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          sudo apt-get install -y python3-setuptools
          python3 -m pip install -r requirements.txt
          python3 -m pip install -e .
      - name: Test
        run: |
          bash run-tests.sh
